# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
includes_dir: _includes
collections:
  posts:
    output:   true

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

plugins: [jekyll-polyglot, jekyll-paginate, jekyll-redirect-from]
# Permalinks
permalink: pretty

include: ['_pages']
exclude: ['LICENSE.md', 'README.md', 'publi.sh', 'Gemfile.lock', 'Gemfile']

# Setup
hyde_theme_id: theme-base-07  # black theme
code_block_max_height: 300px  # code block max height, scroll if exceed

title: Justin's Blog
description:
  zh-CN: 大道不过三两行
  en: If I can't explan it simply, I don't understand it deeply.

paginate: 5
# Custom vars
version: 1.0
# practical values langsep are "|", "•", "·", "-", "–"
langsep: "|"

email: JustinMa@mail.com
github: https://github.com/JustinMaDev
linkedin: https://www.linkedin.com/JustinMaDev

#Polyglot
languages: ["en", "zh-CN"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: false
whitelist:
  - jekyll-redirect-from