# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
collections:
  posts:
    output:   true

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# data
hello:
  en: Hello!
  zh-CN: 你好！

plugins: [jekyll-polyglot, jekyll-paginate, jekyll-redirect-from]
# Permalinks
permalink: pretty

include: ['_pages']
exclude: ['LICENSE.md', 'README.md', 'publi.sh', 'Gemfile.lock', 'Gemfile']

# Setup
title: Justin's Blog
# tagline: 'Justin's Blog'
description:
  中文: 大道不过三两行
  en: If I can't explan it simply, I don't understand it well enough.
#url: https://polyglot.untra.io

paginate: 5
# Custom vars
version: 1.8.1
# practical values langsep are "|", "•", "·", "-", "–"
langsep: "•"

github: https://github.com/JustinMaDev
linkedin: https://www.linkedin.com/JustinMaDev

#Polyglot
languages: ["en", "中文"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: false
whitelist:
  - jekyll-redirect-from